#!/usr/bin/env python3

from __future__ import annotations

import unicodedata
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET_PATH = REPO_ROOT / "addons/claude_agent_sdk/runtime/sessions/claude_unicode_sanitizer.gd"
MAX_PASSES = 10
STRIP_CATEGORIES = ("Cf", "Co", "Cn")


def build_strip_ranges() -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    previous: int | None = None

    for codepoint in range(0x110000):
        category = unicodedata.category(chr(codepoint))
        if category not in STRIP_CATEGORIES:
            continue
        if start is None:
            start = codepoint
            previous = codepoint
            continue
        assert previous is not None
        if codepoint == previous + 1:
            previous = codepoint
            continue
        ranges.append((start, previous))
        start = codepoint
        previous = codepoint

    if start is not None and previous is not None:
        ranges.append((start, previous))
    return ranges


def build_nfkc_map() -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    for codepoint in range(0x110000):
        value = chr(codepoint)
        normalized = unicodedata.normalize("NFKC", value)
        if normalized != value:
            entries.append((codepoint, normalized))
    return entries


def format_strip_ranges(ranges: list[tuple[int, int]]) -> str:
    values: list[str] = []
    for start, end in ranges:
        values.append(str(start))
        values.append(str(end))

    lines: list[str] = []
    width = 8
    for index in range(0, len(values), width):
        chunk = values[index : index + width]
        lines.append("\t" + ", ".join(chunk) + ",")
    return "\n".join(lines)


def format_nfkc_map(entries: list[tuple[int, str]]) -> str:
    def gdscript_string(value: str) -> str:
        parts = ['"']
        for char in value:
            codepoint = ord(char)
            if char == "\\":
                parts.append("\\\\")
            elif char == '"':
                parts.append('\\"')
            elif char == "\n":
                parts.append("\\n")
            elif char == "\r":
                parts.append("\\r")
            elif char == "\t":
                parts.append("\\t")
            elif codepoint < 0x20 or codepoint in (0x0085, 0x2028, 0x2029):
                parts.append("\\u%04x" % codepoint)
            else:
                parts.append(char)
        parts.append('"')
        return "".join(parts)

    lines = [
        "\t%d: %s," % (codepoint, gdscript_string(normalized))
        for codepoint, normalized in entries
    ]
    return "\n".join(lines)


def build_output() -> str:
    strip_ranges = build_strip_ranges()
    nfkc_map = build_nfkc_map()
    python_version = "%d.%d.%d" % (
        sys.version_info.major,
        sys.version_info.minor,
        sys.version_info.micro,
    )
    return """extends RefCounted

# Generated by tools/dev/generate_session_unicode_sanitizer.py.
# Source Unicode data: Python %(python_version)s / unicodedata %(unidata_version)s.
# Do not edit by hand; regenerate from Python's unicodedata tables instead.

const MAX_PASSES := %(max_passes)d
const STRIP_RANGES := [
%(strip_ranges)s
]
const NFKC_SINGLE_CODEPOINT_MAP := {
%(nfkc_map)s
}


static func sanitize(value: String) -> String:
\tvar current := value
\tfor _i in range(MAX_PASSES):
\t\tvar next := ""
\t\tfor j in range(current.length()):
\t\t\tvar code := current.unicode_at(j)
\t\t\tif _should_strip_codepoint(code):
\t\t\t\tcontinue
\t\t\tif NFKC_SINGLE_CODEPOINT_MAP.has(code):
\t\t\t\tnext += str(NFKC_SINGLE_CODEPOINT_MAP[code])
\t\t\telse:
\t\t\t\tnext += char(code)
\t\tif next == current:
\t\t\treturn next
\t\tcurrent = next
\treturn current


static func _should_strip_codepoint(code: int) -> bool:
\tfor i in range(0, STRIP_RANGES.size(), 2):
\t\tvar range_start := int(STRIP_RANGES[i])
\t\tif code < range_start:
\t\t\treturn false
\t\tvar range_end := int(STRIP_RANGES[i + 1])
\t\tif code <= range_end:
\t\t\treturn true
\treturn false
""" % {
        "max_passes": MAX_PASSES,
        "python_version": python_version,
        "unidata_version": unicodedata.unidata_version,
        "strip_ranges": format_strip_ranges(strip_ranges),
        "nfkc_map": format_nfkc_map(nfkc_map),
    }


def main() -> None:
    TARGET_PATH.write_text(build_output(), encoding="utf-8")


if __name__ == "__main__":
    main()
